name: Security Scan

on:
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan httpd image
        run: |
          /usr/bin/time -f "%e" -o httpd_time.txt trivy image --severity HIGH,CRITICAL -f json -o trivy-report-httpd.json httpd:2.4.49
          echo "httpd_2.4.49_scan_time $(cat httpd_time.txt)" >> scan_times.txt

      - name: Scan nginx image
        run: |
          /usr/bin/time -f "%e" -o nginx_time.txt trivy image --severity HIGH,CRITICAL -f json -o trivy-report-nginx.json nginx:1.15
          echo "nginx_1.15_scan_time $(cat nginx_time.txt)" >> scan_times.txt

      - name: Scan mysql image
        run: |
          /usr/bin/time -f "%e" -o mysql_time.txt trivy image --severity HIGH,CRITICAL -f json -o trivy-report-mysql.json mysql:5.5
          echo "mysql_5.5_scan_time $(cat mysql_time.txt)" >> scan_times.txt

      - name: Scan wordpress image
        run: |
          /usr/bin/time -f "%e" -o wordpress_time.txt trivy image --severity HIGH,CRITICAL -f json -o trivy-report-wordpress.json wordpress:4.9.8
          echo "wordpress_4.9.8_scan_time $(cat wordpress_time.txt)" >> scan_times.txt

      - name: Scan web-dvwa image
        run: |
          /usr/bin/time -f "%e" -o web-dvwa_time.txt trivy image --severity HIGH,CRITICAL -f json -o trivy-report-web-dvwa.json vulnerables/web-dvwa
          echo "vulnerables_web-dvwa_scan_time $(cat web-dvwa_time.txt)" >> scan_times.txt

      - name: Scan juice-shop image
        run: |
          /usr/bin/time -f "%e" -o juice-shop_time.txt trivy image --severity HIGH,CRITICAL -f json -o trivy-report-juice-shop.json bkimminich/juice-shop
          echo "bkimminich_juice-shop_scan_time $(cat juice-shop_time.txt)" >> scan_times.txt

      - name: Scan Kubernetes configs
        run: |
          /usr/bin/time -f "%e" -o k8s_time.txt trivy config --severity LOW,MEDIUM,HIGH,CRITICAL -f json -o trivy-report-k8s.json k8s/
          echo "k8s_scan_time $(cat k8s_time.txt)" >> scan_times.txt

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Run Analysis Script
        run: python3 analyze_trivy.py

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: |
            trivy-report-*.json
            scan_times.txt
            *_time.txt
