name: Security Scan

on:
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan httpd image
        run: |
          /usr/bin/time -f "httpd_2.4.49_scan_time %e" trivy image --severity HIGH,CRITICAL -f json -o trivy-report-httpd.json httpd:2.4.49 2>> scan_times.txt

      - name: Scan nginx image
        run: |
          /usr/bin/time -f "nginx_1.15_scan_time %e" trivy image --severity HIGH,CRITICAL -f json -o trivy-report-nginx.json nginx:1.15 2>> scan_times.txt

      - name: Scan mysql image
        run: |
          /usr/bin/time -f "mysql_5.5_scan_time %e" trivy image --severity HIGH,CRITICAL -f json -o trivy-report-mysql.json mysql:5.5 2>> scan_times.txt

      - name: Scan wordpress image
        run: |
          /usr/bin/time -f "wordpress_4.9.8_scan_time %e" trivy image --severity HIGH,CRITICAL -f json -o trivy-report-wordpress.json wordpress:4.9.8 2>> scan_times.txt

      - name: Scan web-dvwa image
        run: |
          /usr/bin/time -f "vulnerables_web-dvwa_scan_time %e" trivy image --severity HIGH,CRITICAL -f json -o trivy-report-web-dvwa.json vulnerables/web-dvwa 2>> scan_times.txt

      - name: Scan juice-shop image
        run: |
          /usr/bin/time -f "bkimminich_juice-shop_scan_time %e" trivy image --severity HIGH,CRITICAL -f json -o trivy-report-juice-shop.json bkimminich/juice-shop 2>> scan_times.txt

      - name: Scan Kubernetes configs
        run: |
          /usr/bin/time -f "k8s_scan_time %e" trivy config --severity LOW,MEDIUM,HIGH,CRITICAL -f json -o trivy-report-k8s.json k8s/ 2>> scan_times.txt

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Run Analysis Script
        run: python3 analyze_trivy.py

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: |
            trivy-report-*.json
            scan_times.txt
